name: node-js-ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  # Verify that prettier passes
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.28.0
      - uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
      - name: Install dependencies and run eslint
        run: |
          pnpm install
          pnpm prettier-check

  # Verify that ESLint passes
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.28.0
      - uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
      - name: Install dependencies and run eslint
        run: |
          pnpm install
          pnpm eslint

  test:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.28.0
      - name: Test
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: |
          pnpm install
          pnpm test
